name: CI

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build docker image
        run: docker build -t ghcr.io/whywelive/actions-395/node-image:latest ./node/

      - name: Push docker image
        run: docker push ghcr.io/whywelive/actions-395/node-image:latest
